hoopflow:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      user: "{{ env_var('POSTGRES_USER', 'hoopflow_user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'hoopflow_password') }}"
      port: "{{ env_var('POSTGRES_PORT', 5432) | int }}"
      dbname: "{{ env_var('POSTGRES_DB', 'hoopflow') }}"
      schema: public
      threads: 4